name: StonedZombie
version: 4.0
description: Stoneharry's Zombie's Vs Human's plugin.
author: Stoneharry
main: stoneharry.zvh.Main
commands:
    myscore:
      description: Returns your personal score.
    playgame:
      description: Teleports you to the zombies vs humans minigame.