name: StonedZombie
version: 3.0
description: Stoneharry's Zombie's Vs Human's plugin.
author: Stoneharry
main: stoneharry.zvh.Main
commands:
    myscore:
      description: Returns your personal score.
      aliases: [myscor, mysco, mysc, mys, my, m]